---
# handlers file

- name: "ZDM set file permissions"
  shell: |
    find '{{ zdm_rolebase_dir }}' -maxdepth 3 -type f -name '*.pyc' -delete;
    find '{{ zdm_rolebase_dir }}' -maxdepth 1 -type f -name '*.py' -exec chmod 755 {} \;
    find '{{ zdm_rolebase_dir }}' -maxdepth 1 -type f -name '*.sh' -exec chmod 755 {} \;
    find '{{ zdm_rolebase_dir }}' -mindepth 2 -type f -exec chmod 644 {} \;
