---
# defaults vars file

zdm_modules_enabled: []

# memcached ------------------------------------------------------------------------------------------------------------
zdm_cnf_memcached_version: "1.4.15"
zdm_cnf_memcached_tool_cmd: "memcached-tool"
zdm_cnf_memcached_addr: "127.0.0.1:11211"

# conntrack ------------------------------------------------------------------------------------------------------------
zdm_cnf_conntrack_version: "1.4.4"
zdm_cnf_conntrack_abs_path: "/usr/sbin/conntrack"
zdm_cnf_conntrack_cmd: "sudo {{ zdm_cnf_conntrack_abs_path }}"

# iostat ---------------------------------------------------------------------------------------------------------------
zdm_cnf_iostat_version: "10.1.5"
zdm_cnf_iostat_discovery_cmd: |-
  iostat -Nk 2>&1 | sed -e '1,/^Device/d' | awk '/.../ {print $1}' | sed -e '/^\([hsv]d[a-z]\|cciss\|nvme\)/!d'; exit $PIPESTATUS
# With device mapper (dm):
# zdm_cnf_iostat_discovery_cmd: |-
#   iostat -Nk 2>&1 | sed -e '1,/^Device/d' | awk '/.../ {print $1}' | sed -e '/^\(fd0\|sr0\|loop\|docker\-[0-9]\+:\)/d'; exit $PIPESTATUS
zdm_cnf_iostat_stat_cmd: "iostat -Nk 2>&1"
zdm_cnf_iostat_util_cmd: "iostat -Nxd 1 2 2>&1"
zdm_cnf_iostat_cache_ttl: 29

# nginx ----------------------------------------------------------------------------------------------------------------
zdm_cnf_nginx_version: "1.10.3"
zdm_cnf_nginx_stub_status_url: "http://127.0.0.1/stub_status"
zdm_cnf_nginx_allow_redirects: True
zdm_cnf_nginx_cache_ttl: 59

# apache ---------------------------------------------------------------------------------------------------------------
zdm_cnf_apache_version: "2.4.6"
zdm_cnf_apache_server_status_url: "http://127.0.0.1/server-status"
zdm_cnf_apache_allow_redirects: True
zdm_cnf_apache_cache_ttl: 59

# ping -----------------------------------------------------------------------------------------------------------------
zdm_cnf_ping_version: "20121221"
zdm_cnf_ping_cmd: "ping -n -W5 -i 0.3 -c4 '{ADDR}' 2>&1"
zdm_cnf_ping_cache_ttl: 29

# gitlab ---------------------------------------------------------------------------------------------------------------
zdm_cnf_gitlab_version: "4"
zdm_cnf_gitlab_cache_ttl: 29
zdm_cnf_gitlab_api_url: "http://example.com/api/v4"
zdm_cnf_gitlab_private_token: "*****"
zdm_cnf_gitlab_runners_discovery_params: |-
  {
    'per_page': 100,
    'scope': "active",
  }
